models/GraphForm.php
<?php

namespace app\models;

use yii\base\Model;

class GraphForm extends Model
{
    public $date_from;
    public $date_to;

    /**
     * Названия атрибутов
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'date_from' => 'С',
            'date_to' => 'По',
        ];
    }

    /**
     * Правила валидации
     *
     * @return array
     */
    public function rules()
    {
        return [
            [['date_from','date_to'],'required'],
            [ ['date_from', 'date_to'],'date', 'format'=>'yy-mm-dd'],
        ];
    }

    /**
     * Добавление задачи в таблицу tasks
     *
     * Задача представляет собой JSON объект с периодом времени,
     * за который нужно составлять график.
     *
     * @return bool - true, если сохранение в БД произошло
     */
    public function addTask(){
        $taskArr = array();
        $taskArr['date_from'] = $this->date_from;
        $taskArr['date_to'] = $this->date_to;
        $taskArrJSON = json_encode($taskArr);

        $task = new Task();
        $task->text = $taskArrJSON;
        $task->processed = 0;
        return $task->save();
    }
}

controllers/GraphController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 15.03.19
 * Time: 10:53
 */

namespace app\controllers;

use app\models\Absence;
use app\models\Shift;
use app\models\Task;
use app\models\User;
use Yii;
use yii\web\Controller;
use app\models\GraphForm;

class GraphController extends Controller
{
    /**
     * Определение пользователем периода времени для составления графика
     *
     * @return string|\yii\web\Response
     */
    public function actionIndex(){
        $graphForm = new GraphForm();
        if(isset($_POST['GraphForm'])){
            $graphForm->attributes = Yii::$app->request->post('GraphForm');
            if($graphForm->validate() && $graphForm->addTask()){
                return $this->redirect('/graph/absence');
            }
        }
        return $this->render('index', compact('graphForm'));
    }

    /**
     * Отображение таблицы для возможности отметки об отсутствии
     *
     * @return string
     */
    public function actionAbsence(){
        $tasks = Task::find()->orderBy(['id' => SORT_DESC])->one();
        $dates = json_decode($tasks['text'], true);
        $diffDates = (strtotime($dates['date_to']) - strtotime($dates['date_from']))/86400;
        $date_from = strtotime($dates['date_from']);

        $users = User::find()->select(['fio','id'])->where(['group' => 3])
            ->orWhere(['group' => 9])->orWhere(['group' => 13])->asArray()->all();


        return $this->render('absence', compact('diffDates', 'users','date_from'));
    }

    /**
     * Отметка об отсутствии
     *
     * @param $id - идентификатор пользователя
     * @param $date - дата отсутствия
     * @return bool
     */
    public function actionNoteAbsence($id, $date){
        $absence_model = new Absence();
        $absence_model->noteAbsence($id, $date);
        return true;
    }

    /**
     * Отображение рабочего графика
     *
     * @return string
     */
    public function actionShift(){
        $tasks = Task::find()->orderBy(['id' => SORT_DESC])->one();
        $shifts = Shift::find()->asArray()->with('user')->orderBy('id_user')->all();

        $dates = json_decode($tasks['text'], true);
        $diffDates = (strtotime($dates['date_to']) - strtotime($dates['date_from']))/86400;
        $date_from = strtotime($dates['date_from']);

       //ini_set('memory_limit', '1000M');
       //ini_set('max_execution_time', 900);
        $shiftsCpy = $shifts;

        return $this->render('shift', compact(  'shifts', 'diffDates', 'date_from', 'shiftsCpy'));
    }
}

controllers/TaskController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19.03.19
 * Time: 9:04
 */

namespace app\controllers;

use app\models\Task;
use yii\helpers\Json;
use yii\web\Controller;

class TaskController extends Controller
{
    /**
     * Отправка задач
     *
     * @return
     */
    public function actionIndex()
    {
        $taskModel = new Task();
        $query = Task::find()->select(['id','text'])->where(['processed' => 0])->all();
        $result = array();
        $result = Json::decode($query[count($query)-1]['text']);
        $result['id'] = $query[count($query)-1]['id'];
        $url = '10.80.18.199:8080';
        $resultJSON = json_encode($result);
        $taskModel->transferCurl($url, $resultJSON);
        return $this->redirect('/graph/shift');
    }

}

views/graph/absence.php
<?php

$this->title = 'Отсутствие';

use yii\helpers\Url;
?>

<section class="absence">
    <div class="container-fluid">
        <h3 align="center">Отсутствие</h3>
        <a href="<?= Url::to(['/task/index']) ?>" class="btn btn-primary">Начать построение графика</a>
        <a href="<?= Url::to(['/graph/index']) ?>" class="btn btn-danger">Изменить диапазон дат</a>
        <a href="<?= Url::to(['/graph/absence']) ?>" class="btn btn-danger">Удалить отметки об отсутствии</a>
        <div class="absence-block">
            <table width="100%" cellpadding="5">
                <tr>
                    <th>ФИО</th>
                    <?php for($i = 0; $i < $diffDates; $i++):
                            $date_unix = $date_from + 86400*$i;
                            $date = date('d', $date_unix);
                    ?>
                        <th><?= $date;?></th>
                    <?php endfor; ?>
                </tr>
                <?php
                if(!empty($users))
                    foreach ($users as $user):
                        ?>
                        <tr>
                            <td><?=$user['fio'];?></td>
                            <?php for($i = 0; $i < $diffDates; $i++):
                                $date_unix = $date_from + 86400*$i;
                                $date = date('Y-m-d', $date_unix);
                            ?>
                                <td><a class="note_absence" data-id="<?=$user['id'];?>"
                                       data-date="<?=$date;?>" href="<?= Url::to(['/graph/note-absence',
                                        'id' => $user['id']]) ?>">
                                        <i class="fa fa-plus"></i></a></td>
                            <?php endfor; ?>
                        </tr>
                    <?php endforeach; ?>
            </table>
        </div>
    </div>
</section>

views/graph/index.php
<?php
$this->title = 'Составление графика';

use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

?>
<div class="container-fluid">
    <div class="col-md-2 col-md-offset-5">
        <h3 align="center">Составление графика</h3>
        <?php
        $form = ActiveForm::begin(['class' => 'form-horizontal', 'id' => 'drafting_graph']);
        ?>

        <?= $form->field($graphForm, 'date_from')->widget(DatePicker::class, [
            'type' => DatePicker::TYPE_INPUT,
            'pluginOptions' => [
                'autoclose'=>true,
                'format' => 'yyyy-mm-dd'
            ]
        ]); ?>
        <?= $form->field($graphForm, 'date_to')->widget(DatePicker::class, [
            'type' => DatePicker::TYPE_INPUT,
            'pluginOptions' => [
                'autoclose'=>true,
                'format' => 'yyyy-mm-dd'
            ]
        ]); ?>
        <button type="submit" class="btn btn-primary">Составить график</button>
        <?php
        ActiveForm::end();
        ?>
    </div>
</div>

views/graph/shift.php
<?php
$this->title = 'График';

$amountDays = date("t");
?>
<section class="shifts">
    <div class="container-fluid">
        <h3 align="center">Список смен</h3>
        <div class="shift-block">
            <table width="100%" cellpadding="5">
                <tr>
                    <th>ФИО</th>
                    <?php for($i = 0; $i < $diffDates; $i++):
                        $date_unix = $date_from + 86400*$i;
                        $date = date('d', $date_unix);
                        ?>
                        <th>
                            <?= $date;?>
                        </th>
                    <?php endfor; ?>
                </tr>
                <?php
                    $flagFound = 0;
                    $j = 0;
                    $buffer = array();
                    $bufferDate = array();
                    foreach ($shifts as $shift):
                        if(!in_array($shift['user']['fio'], $buffer)):
                            $buffer[$j] = $shift['user']['fio'];
                            $j++;
                        ?>
                        <tr>
                            <td><?= $shift['user']['fio']; ?></td>
                            <?php for($i = 0; $i < $diffDates; $i++):
                                $date_unix = $date_from + 86400*$i;
                                $date = date('Y-m-d', $date_unix);
                                for($m = 0; $m < count($shiftsCpy); $m++){
                                    if(($buffer[$j-1] == $shiftsCpy[$m]['user']['fio'])
                                        && ($date == date('Y-m-d', strtotime($shiftsCpy[$m]['date_start_work'])))){
                                        $flagFound = 1;
                                        $bufferDate['date_start_work'] = date('H', strtotime($shiftsCpy[$m]['date_start_work']));
                                        $bufferDate['date_end_work'] = date('H', strtotime($shiftsCpy[$m]['date_end_work']));
                                    }
                                }
                                ?>
                                <?php if($flagFound == 1):
                                        $flagFound = 0;
                                ?>
                                    <td><?= $bufferDate['date_start_work'].'-'.$bufferDate['date_end_work'];?></td>
                                    <?php else: ?>
                                    <td><?= 'В' ?></td>
                                <?php endif;?>
                            <?php endfor; ?>
                        </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
            </table>
        </div>
    </div>
</section>